### ISSUE TITLE
Can you push your model to google drive or others? I cannot download your pre-trained model to test. Thanks+

### ISSUE THREAD

**Issue by Cabbagehust2507** [Pay20Y/GCAN#6]

**Comment by Pay20Y** [comment]
Sure, here is the [Google drive link](https://drive.google.com/file/d/15fI29nihXqoDHFKnNX3omgf2K6MFRKjC/view?usp=sharing)

**Comment by Cabbagehust2507** [comment]
> Sure, here is the [Google drive link](https://drive.google.com/file/d/15fI29nihXqoDHFKnNX3omgf2K6MFRKjC/view?usp=sharing)

Thank you in advance :D

**Comment by Cabbagehust2507** [comment]
@Pay20Y And it requires access approve from you. I've just sent a request.
